services:
    phlexible_element_redirect.redirect_manager:
        class: Phlexible\Bundle\ElementRedirectBundle\Doctrine\RedirectManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@phlexible_tree.tree_manager"
            - "@event_dispatcher"

    # event listeners
    phlexible_element_redirect.listener.node:
        class: Phlexible\Bundle\ElementRedirectBundle\EventListener\NodeListener
        arguments:
            - "@phlexible_element_redirect.redirect_manager"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_element_redirect.listener.dispatch:
        class: Phlexible\Bundle\ElementRedirectBundle\EventListener\DispatchListener
        arguments:
            - "@phlexible_element_redirect.redirect_manager"
        tags:
            - {name: kernel.event_subscriber}

    # role providers
    phlexible_element_redirect.role_provider:
        class: Phlexible\Bundle\ElementRedirectBundle\RoleProvider\ElementRedirectRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
