services:
    phlexible_redirect.redirect_manager:
        class: Phlexible\Bundle\RedirectBundle\Doctrine\RedirectManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@phlexible_tree.tree_manager"
            - "@event_dispatcher"

    # event listeners
    phlexible_redirect.listener.node:
        class: Phlexible\Bundle\RedirectBundle\EventListener\NodeListener
        arguments:
            - "@phlexible_redirect.redirect_manager"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_redirect.listener.dispatch:
        class: Phlexible\Bundle\RedirectBundle\EventListener\RedirectListener
        arguments:
            - "@phlexible_redirect.redirect_manager"
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_siteroot.siteroot_request_matcher"
            - "@router"
        tags:
            - {name: kernel.event_subscriber}

    # role providers
    phlexible_redirect.role_provider:
        class: Phlexible\Bundle\RedirectBundle\RoleProvider\ElementRedirectRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
